hospitalcrm/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from hospitalcrm.settings import STATIC_ROOT, STATIC_URL
from patients.views import LandingPageView, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, 
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('patients/',include('patients.urls', namespace="patients")),
    path('physicians/',include('physicians.urls', namespace="physicians")),
    path('login/', LoginView.as_view(),name='login'),
    path('logut/',LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name="signup"),

    path('reset-password/',PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patients/urls.py
from django.urls import path
from .views import (
    AssignPhysicianView, PatientListView,
    PatientDetailView, PatientCreateView, PatientUpdateView,
    PatientDeleteView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView
)
app_name = "patients"

urlpatterns = [
    path('', PatientListView.as_view(), name="patient-list"),
    path('<int:pk>/', PatientDetailView.as_view(), name="patient-detail"),
    path('create/', PatientCreateView.as_view(), name="patient-create"),
    path('<int:pk>/update/', PatientUpdateView.as_view(), name="patient-update"),
    path('<int:pk>/delete/', PatientDeleteView.as_view(), name="patient-delete"),
    path('<int:pk>/assign-physician/',AssignPhysicianView.as_view(),name="assign-physician"),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='patient-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='patient-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='patient-followup-delete'),
]

physicians/urls.py
from django.urls import path

from patients.models import Department
from physicians.forms import PhysicianDepartmentUpdateForm
from .views import (
    DepartmentCreateView, DepartmentDeleteView, DepartmentDetailView, DepartmentListView, DepartmentUpdateView, PhysicianCreateView, PhysicianDeleteView, PhysicianDepartmentUpdateView, PhysicianDetailView,
     PhysicianListView, PhysicianUpdateView
)

app_name = 'physicians'

urlpatterns = [
    path('',PhysicianListView.as_view(),name="physician-list"),
    path('create/', PhysicianCreateView.as_view(), name="physician-create"),
    path('<int:pk>/', PhysicianDetailView.as_view(), name="physician-detail"),
    path('<int:pk>/update/', PhysicianUpdateView.as_view(), name="physician-update"),
    path('<int:pk>/delete/', PhysicianDeleteView.as_view(), name="physician-delete"),
    path("departments/",DepartmentListView.as_view(), name="department-list"),
    path("departments/<int:pk>/",DepartmentDetailView.as_view(),name="department-detail"),
    path('departments/<int:pk>/update/', DepartmentUpdateView.as_view(), name='department-update'),
    path('departments/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
    path('create-department/', DepartmentCreateView.as_view(), name='department-create'),
    path('<int:pk>/update-department/',PhysicianDepartmentUpdateView.as_view(),name="physician-department-update")
]

physicians/models.py
from django.db import models

# Create your models here.

physicians/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from patients.models import Department, Physician

User = get_user_model()

class PhysicianModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

class PhysicianDepartmentUpdateForm(forms.ModelForm):
    class Meta:
        model = Physician
        fields = (
            'department',
        )

class DepartmentModelForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = (
            'name',
            'abbreviation',
            'description',
        )

physicians/views.py
from audioop import reverse
import random as rand
from re import template
from urllib import request
from django.forms import GenericIPAddressField
from django.shortcuts import render, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from patients.models import Department, Physician
from .forms import DepartmentModelForm, PhysicianDepartmentUpdateForm, PhysicianModelForm
from .mixins import TeamleadRequiredMixin
from django.core.mail import send_mail

class PhysicianListView(TeamleadRequiredMixin, generic.ListView):
    template_name = "physicians/physician_list.html"

    def get_queryset(self):
        team = self.request.user.userprofile
        return Physician.objects.filter(team=team)


class PhysicianCreateView(TeamleadRequiredMixin, generic.CreateView):
    template_name = "physicians/physician_create.html"
    form_class = PhysicianModelForm

    def get_success_url(self):
        return reverse("physicians:physician-list")
    
    def form_valid(self,form):
        user = form.save(commit=False)
        user.is_physician = True
        user.is_teamlead = False
        user.set_password(f"{rand.randint(0,100000)}")
        user.save()
        Physician.objects.create(
            user=user,
            team=self.request.user.userprofile,

        )

        send_mail(
            subject="This is not a scam. You are now a physician!!!",
            message="Congratulation. You are now a physician of Medicare Hospital.",
            from_email="admin@test.com",
            recipient_list=[
                user.email
            ]
        )
        # physician.team = self.request.user.userprofile
        # physician.save()
        return super(PhysicianCreateView,self).form_valid(form)

class PhysicianDetailView(TeamleadRequiredMixin, generic.DetailView):
    template_name = "physicians/physician_detail.html"
    context_object_name = "physician"

    def get_queryset(self):
        user = self.request.user
        queryset = Physician.objects.filter(team=user.userprofile)
        
        return queryset

class PhysicianUpdateView(TeamleadRequiredMixin, generic.UpdateView):
    template_name = "physicians/physician_update.html"
    form_class = PhysicianModelForm

    def get_success_url(self):
        return reverse("physicians:physician-list")

    def get_queryset(self):
        user = self.request.user
        queryset = Physician.objects.filter(team=user.userprofile) 
        print(queryset)
        return queryset
    
class PhysicianDeleteView(TeamleadRequiredMixin, generic.DeleteView):
    template_name = "physicians/physician_delete.html"
    context_object_name = "physician"

    def get_queryset(self):
        team = self.request.user.userprofile
        return Physician.objects.filter(team=team)

    def get_success_url(self):
        return reverse("physicians:physician-list")

class DepartmentListView(LoginRequiredMixin, generic.ListView):
    template_name = "physicians/department_list.html"
    context_object_name = "departments"

    def get_context_data(self, **kwargs):
        context = super(DepartmentListView,self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_teamlead:
            queryset =Physician.objects.filter(
                team=user.userprofile,
            )
        else:
            queryset = Physician.objects.filter(
                team=user.physician.team,
            )
        context.update({
            "unassigned_physicians" : queryset.filter(department__isnull=True),
            "unassigned_physicians_count" : queryset.filter(department__isnull=True).count(),
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_teamlead:
            queryset = Department.objects.filter(
                team_lead=user.userprofile,
            )
        else:
            queryset = Department.objects.filter(
                team_lead=user.team,
            )
        
        return queryset

class DepartmentDetailView(LoginRequiredMixin, generic.DeleteView):

    template_name = "physicians/department_detail.html"
    context_object_name = "department"

    def get_queryset(self):
        user = self.request.user
        if user.is_teamlead:
            queryset = Department.objects.filter(
                team_lead=user.userprofile,
            )
        else:
            queryset = Department.objects.filter(
                team_lead=user.team,
            )
        
        return queryset

class PhysicianDepartmentUpdateView(TeamleadRequiredMixin, generic.UpdateView):
    template_name = "physicians/physician_department_update.html"
    form_class = PhysicianDepartmentUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_teamlead:
            queryset = Physician.objects.filter(team=user.userprofile)
        else:
            queryset = Physician.objects.filter(team=user.team)
            queryset = queryset.filter(user=user)
        return queryset

    def get_success_url(self):
        return reverse("physicians:physician-detail", kwargs={"pk":self.get_object().id})

class DepartmentCreateView(TeamleadRequiredMixin, generic.CreateView):
    template_name = "physicians/department_create.html"
    form_class = DepartmentModelForm

    def get_success_url(self):
        return reverse("physicians:department-list")

    def form_valid(self, form):
        department = form.save(commit=False)
        department.team_lead = self.request.user.userprofile
        department.save()
        return super(DepartmentCreateView, self).form_valid(form)


class DepartmentUpdateView(TeamleadRequiredMixin, generic.UpdateView):
    template_name = "physicians/department_update.html"
    form_class = DepartmentModelForm

    def get_success_url(self):
        return reverse("physicians:department-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_teamlead:
            queryset = Department.objects.filter(
                team_lead=user.userprofile
            )
        else:
            queryset = Department.objects.filter(
                team_lead=user.team
            )
        return queryset


class DepartmentDeleteView(TeamleadRequiredMixin, generic.DeleteView):
    template_name = "physicians/department_delete.html"

    def get_success_url(self):
        return reverse("physicians:department-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_teamlead:
            queryset = Department.objects.filter(
                team_lead=user.userprofile
            )
        else:
            queryset = Department.objects.filter(
                team_lead=user.team
            )
        return queryset

physicians/templates/physicians/department_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'physicians:department-list' %}">Back</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Add a new department</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

physicians/templates/physicians/department_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'physicians:department-list' %}">Back</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Are you sure you want to delete {{ object.name }}?</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

physicians/templates/physicians/department_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">

        <div class="w-2/3 mx-auto">
            <a class="hover:text-blue-500" href="{% url 'physicians:department-list' %}">Back</a>
            <hr />
        </div>
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
                {{ department.name }}
            </h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                The physcian of {{department.name}} department
            </p>
            <a href="{% url 'physicians:department-update' department.pk %}" class="hover:text-blue-500">Update</a>
            <a href="{% url 'physicians:department-delete' department.pk %}" class="hover:text-blue-500">Delete</a>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap mb-3">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                            Department Information
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <th>
                        <div class="flex border-t border-gray-300 py-2">
                            <span class="text-gray-500">Description</span>
                            <span class="ml-auto text-gray-900">{{ department.description }}</span>
                        </div>
                        <div class="flex border-t border-gray-300 py-2">
                            <span class="text-gray-500">Abbreviation</span>
                            <span class="ml-auto text-gray-900">{{ department.abbreviation }}</span>
                        </div>
                    </th>
                    
                </tbody>
                
            </table>

            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                            Full Name
                        </th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">
                            Email
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for physician in department.physicians.all %}
                    <tr>
                        <td class="px-4 py-3">
                            <a class="hover:text-blue-500"
                                href="{% url 'physicians:physician-detail' physician.pk %}">{{physician.user.first_name}}
                                {{physician.user.last_name}}</a>
                        </td>
                        <td class="px-4 py-3">{{physician.user.email}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>


{% endblock content %}

physicians/templates/physicians/department_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Departments</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                Available departments in Medicare Hospital
            </p>
            
        </div>
        
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <div class="text-right pb-2">
                <a href="{% url 'physicians:department-create' %}" class="hover:text-blue-500">Add a new Department</a>
            </div>
            
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">
                            Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">
                            Abbreviation</th>
                    </tr>
                </thead>
                <tbody>
                    {% for department in departments %}
                    <tr>
                        <td class="px-4 py-3">
                            <a class="hover:text-blue-500"
                                href="{% url 'physicians:department-detail' department.pk %}">{{ department.name }}</a>
                        </td>
                        <td class="px-4 py-3">{{department.abbreviation}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>


{% endblock content %}

physicians/templates/physicians/department_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'physicians:department-list' %}">Back</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update {{ object.name }}</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

physicians/templates/physicians/physician_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-md mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'physicians:physician-list' %}">Back</a>
    </div>
    
    <hr />
    <h1 class="text-4xl text-gray-800" >Create a new physician</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
</div>
    
    

{% endblock content %}

physicians/templates/physicians/physician_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <a href="{% url 'physicians:physician-list' %}">Back</a>
    <hr />
    <h1>Deleting patient </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Confirm</button>
    </form>
    

{% endblock content %}

physicians/templates/physicians/physician_department_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">PHYSICIAN</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ physician.user }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'physicians:physician-detail' physician.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
                    <a href="{% url 'physicians:physician-department-update' physician.pk%}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Department</a>
                    <a href="{% url 'physicians:physician-update' physician.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
                </div>
                <form form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit"
                        class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

physicians/templates/physicians/physician_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">PHYSICIAN</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ physician.user }}</h1>
            <div class="flex mb-4">
                <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
                <a href="{% url 'physicians:physician-department-update' physician.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Department</a>
                <a href="{% url 'physicians:physician-update' physician.pk%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ physician.user.first_name }} {{ physician.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ physician.user.email }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Join date</span>
                <span class="ml-auto text-gray-900">{{ physician.user.date_joined }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

physicians/templates/physicians/physician_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Physicians</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'physicians:physician-create' %}">Add a new physician</a>
            </div>
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Full Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Department
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            Action <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for physician in object_list %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a href="{% url 'physicians:physician-detail' physician.pk %}" class="text-indigo-600 hover:text-indigo-900">{{ physician.user.first_name }} {{ physician.user.last_name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ physician.user.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ physician.department }}
                                </td>
                                <td class="text-center px-6 py-4 whitespace-nowrap text-sm font-medium">
                                    <a href="{% url 'physicians:physician-update' physician.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        {% empty %}

                        <p>There are currently no agents</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>

    </div>
  </section>


{% endblock content %}

physicians/templates/physicians/physician_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">PHYSICIAN</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ physician.user }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'physicians:physician-detail' physician.pk %}"
                class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
            <a href="{% url 'physicians:physician-department-update' physician.pk%}"
                class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Department</a>
            <a href="{% url 'physicians:physician-update' physician.pk %}"
                class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'physicians:physician-delete' physician.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}