hospitalcrm/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from hospitalcrm.settings import STATIC_ROOT, STATIC_URL
from patients.views import LandingPageView, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, 
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('patients/',include('patients.urls', namespace="patients")),
    path('physicians/',include('physicians.urls', namespace="physicians")),
    path('login/', LoginView.as_view(),name='login'),
    path('logut/',LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name="signup"),

    path('reset-password/',PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patients/urls.py
from django.urls import path
from .views import (
    AssignPhysicianView, PatientListView,
    PatientDetailView, PatientCreateView, PatientUpdateView,
    PatientDeleteView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView
)
app_name = "patients"

urlpatterns = [
    path('', PatientListView.as_view(), name="patient-list"),
    path('<int:pk>/', PatientDetailView.as_view(), name="patient-detail"),
    path('create/', PatientCreateView.as_view(), name="patient-create"),
    path('<int:pk>/update/', PatientUpdateView.as_view(), name="patient-update"),
    path('<int:pk>/delete/', PatientDeleteView.as_view(), name="patient-delete"),
    path('<int:pk>/assign-physician/',AssignPhysicianView.as_view(),name="assign-physician"),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='patient-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='patient-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='patient-followup-delete'),
]

physicians/urls.py
from django.urls import path

from patients.models import Department
from physicians.forms import PhysicianDepartmentUpdateForm
from .views import (
    DepartmentCreateView, DepartmentDeleteView, DepartmentDetailView, DepartmentListView, DepartmentUpdateView, PhysicianCreateView, PhysicianDeleteView, PhysicianDepartmentUpdateView, PhysicianDetailView,
     PhysicianListView, PhysicianUpdateView
)

app_name = 'physicians'

urlpatterns = [
    path('',PhysicianListView.as_view(),name="physician-list"),
    path('create/', PhysicianCreateView.as_view(), name="physician-create"),
    path('<int:pk>/', PhysicianDetailView.as_view(), name="physician-detail"),
    path('<int:pk>/update/', PhysicianUpdateView.as_view(), name="physician-update"),
    path('<int:pk>/delete/', PhysicianDeleteView.as_view(), name="physician-delete"),
    path("departments/",DepartmentListView.as_view(), name="department-list"),
    path("departments/<int:pk>/",DepartmentDetailView.as_view(),name="department-detail"),
    path('departments/<int:pk>/update/', DepartmentUpdateView.as_view(), name='department-update'),
    path('departments/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
    path('create-department/', DepartmentCreateView.as_view(), name='department-create'),
    path('<int:pk>/update-department/',PhysicianDepartmentUpdateView.as_view(),name="physician-department-update")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MEDICARE HOSPITAL</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}
        
        {% endblock content %}
    </div>
    {% include "scripts.html" %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/hospital.jpg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            Medicare Hospital
        </h1>
        <p class="mb-8 leading-relaxed">
          Your health, Our priority
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Login to get started
          </a>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a href="{% url 'landing-page' %}"class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round"
        stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
        viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg> -->
      <span class="ml-3 text-xl">MEDICARE HOSPITAL</span>
    </a>

    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if request.user.is_authenticated %}
        <a href="{% url 'patients:patient-list' %}" class="mr-5 hover:text-gray-900">Patients</a>
        {% if request.user.is_teamlead %}
          <a href="{% url 'physicians:physician-list' %}" class="mr-5 hover:text-gray-900">Physicians</a>
          <a href="{% url 'physicians:department-list' %}" class="mr-5 hover:text-gray-900">Departments</a>
        {% endif %}
        {% else %}
        <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
      {% endif %}
    </nav>

    {% if request.user.is_authenticated %}
    <p class="text-blue-500 hover:text-blue-300">Login: {{ request.user.username }}</p>
    <a href="{% url 'logout' %}"
      class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 ml-2 md:mt-0">Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a href="{% url 'login' %}"
      class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-blue-200 rounded text-base mt-4 md:mt-0">Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>

templates/second_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Page Title</title>
</head>
<body>

    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
    <ul>
        {% for patient in patients %}
        <li>
            {{patient}}
        </li>
        {% endfor %}
    </ul>

</body>
</html>