hospitalcrm/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from hospitalcrm.settings import STATIC_ROOT, STATIC_URL
from patients.views import LandingPageView, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, 
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('patients/',include('patients.urls', namespace="patients")),
    path('physicians/',include('physicians.urls', namespace="physicians")),
    path('login/', LoginView.as_view(),name='login'),
    path('logut/',LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name="signup"),

    path('reset-password/',PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patients/urls.py
from django.urls import path
from .views import (
    AssignPhysicianView, PatientListView,
    PatientDetailView, PatientCreateView, PatientUpdateView,
    PatientDeleteView, FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView
)
app_name = "patients"

urlpatterns = [
    path('', PatientListView.as_view(), name="patient-list"),
    path('<int:pk>/', PatientDetailView.as_view(), name="patient-detail"),
    path('create/', PatientCreateView.as_view(), name="patient-create"),
    path('<int:pk>/update/', PatientUpdateView.as_view(), name="patient-update"),
    path('<int:pk>/delete/', PatientDeleteView.as_view(), name="patient-delete"),
    path('<int:pk>/assign-physician/',AssignPhysicianView.as_view(),name="assign-physician"),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='patient-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='patient-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='patient-followup-delete'),
]

patients/models.py
from unicodedata import category
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_teamlead = models.BooleanField(default=True)
    is_physician = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Patient(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    team = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    physician = models.ForeignKey('Physician', null=True, blank=True,on_delete=models.SET_NULL)
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

def handle_upload_follow_ups(instance, filename):
    return f"patient_followups/patient_{instance.patient.pk}/{filename}"


class FollowUp(models.Model):
    patient = models.ForeignKey(Patient, related_name="followups", on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    message = models.TextField(blank=True, null=True)
    file = models.FileField(null=True, blank=True, upload_to=handle_upload_follow_ups)

    def __str__(self):
        return f"{self.patient.first_name} {self.patient.last_name}"

class Physician(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    team = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    department = models.ForeignKey("Department", related_name="physicians" ,null=True, blank=True,on_delete=models.SET_NULL)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class Department(models.Model):
    name = models.CharField(max_length=50)
    abbreviation = models.CharField(max_length=10)
    description = models.CharField(max_length=255)
    team_lead = models.ForeignKey(UserProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

patients/forms.py
from urllib import request
from django import forms
from .models import FollowUp, Patient, Physician, User
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

class PatientModelForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = (
            'first_name',
            'last_name',
            'age',
            'email',
            'phone_number',
            'physician',
        )

class PatientForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

class AssignPhysicianForm(forms.Form):
    physician = forms.ModelChoiceField(queryset=Physician.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        physicians = Physician.objects.filter(team=request.user.userprofile)
        super(AssignPhysicianForm,self).__init__(*args, **kwargs)
        self.fields["physician"].queryset = physicians

class FollowUpModelForm(forms.ModelForm):
    class Meta:
        model = FollowUp
        fields = (
            'message',
            'file'
        )

patients/views.py
from distutils.command.clean import clean
from msilib.schema import ListView
from re import template
from django.shortcuts import render, redirect, reverse
from .models import Patient, Physician, FollowUp
from .forms import AssignPhysicianForm, FollowUpModelForm, PatientForm, PatientModelForm, CustomUserCreationForm
from django.views import generic
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from physicians.mixins import TeamleadRequiredMixin


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"


class PatientListView(LoginRequiredMixin, generic.ListView):
    template_name = "patients/patient_list.html"
    context_object_name = "patients"

    def get_queryset(self):
        user = self.request.user
        if user.is_teamlead:
            queryset = Patient.objects.filter(
                team=user.userprofile,
                physician__isnull=False
            )
        else:
            queryset = Patient.objects.filter(
                team=user.physician.team,
                physician__isnull=False
            )
            #filter for physican that is logged in
            queryset = queryset.filter(physician__user=user)
        
        return queryset

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(PatientListView, self).get_context_data(**kwargs)
        if user.is_teamlead:
            queryset = Patient.objects.filter(
                team=user.userprofile,
                physician__isnull=True
            )
            context.update({
                "unassigned_patients": queryset
            })
        return context


class PatientDetailView(LoginRequiredMixin,generic.DetailView):
    template_name = "patients/patient_detail.html"
    context_object_name = "patient"

    def get_queryset(self):
        user = self.request.user
        #intial queryset of the physician for the entire team
        if user.is_teamlead:
            queryset = Patient.objects.filter(team=user.userprofile)
        else:
            queryset = Patient.objects.filter(team=user.physician.team)
            #filter for physican that is logged in
            queryset = queryset.filter(physician__user=user)
        #print(Patient.objects.filter(team=user.userprofile))
        return queryset


class PatientCreateView(TeamleadRequiredMixin,generic.CreateView):
    template_name = "patients/patient_create.html"
    form_class =  PatientModelForm

    def get_success_url(self):
        return reverse("patients:patient-list")

    def form_valid(self, form):
        patient = form.save(commit=False)
        patient.team = self.request.user.userprofile
        patient.save()
        send_mail(
            subject="A patient has been created",
            message="Go to new site to see the new patient",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        return super(PatientCreateView,self).form_valid(form)

class PatientUpdateView(TeamleadRequiredMixin,generic.UpdateView):
    template_name = "patients/patient_update.html"
    form_class =  PatientModelForm

    def get_queryset(self):
        user = self.request.user
        
        return Patient.objects.filter(team=user.userprofile)

    def get_success_url(self):
        return reverse("patients:patient-list")


class PatientDeleteView(TeamleadRequiredMixin,generic.DeleteView):
    template_name = "patients/patient_delete.html"
    
    def get_queryset(self):
        user = self.request.user
        
        return Patient.objects.filter(team=user.userprofile)

    def get_success_url(self):
        return reverse("patients:patient-list")

class AssignPhysicianView(TeamleadRequiredMixin, generic.FormView):
    template_name = "patients/assign_physician.html"
    form_class = AssignPhysicianForm

    def get_form_kwargs(self, **kwargs):
        kwargs =  super(AssignPhysicianView,self).get_form_kwargs(**kwargs)
        kwargs.update ({
            "request" : self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("patients:patient-list")

    def form_valid(self, form):
        physician = form.cleaned_data['physician']
        patient = Patient.objects.get(id=self.kwargs["pk"])
        patient.physician = physician
        patient.save()
        return super(AssignPhysicianView,self).form_valid(form)

class FollowUpCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "patients/followup_create.html"
    form_class = FollowUpModelForm

    def get_success_url(self):
        return reverse("patients:patient-detail", kwargs={"pk": self.kwargs["pk"]})

    def get_context_data(self, **kwargs):
        context = super(FollowUpCreateView, self).get_context_data(**kwargs)
        context.update({
            "patient": Patient.objects.get(pk=self.kwargs["pk"])
        })
        return context

    def form_valid(self, form):
        patient = Patient.objects.get(pk=self.kwargs["pk"])
        followup = form.save(commit=False)
        followup.patient = patient
        followup.save()
        return super(FollowUpCreateView, self).form_valid(form)

class FollowUpUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "patients/followup_update.html"
    form_class = FollowUpModelForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_teamlead:
            queryset = FollowUp.objects.filter(patient__team=user.userprofile)
        else:
            queryset = FollowUp.objects.filter(patient__team=user.agent.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(patient__physician__user=user)
        return queryset

    def get_success_url(self):
        return reverse("patients:patient-detail", kwargs={"pk": self.get_object().patient.id})

class FollowUpDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = "patients/followup_delete.html"

    def get_success_url(self):
        followup = FollowUp.objects.get(id=self.kwargs["pk"])
        return reverse("patients:patient-detail", kwargs={"pk": followup.patient.pk})

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        if user.is_teamlead:
            queryset = FollowUp.objects.filter(patient__team=user.userprofile)
        else:
            queryset = FollowUp.objects.filter(patient__team=user.physician.team)
            # filter for the agent that is logged in
            queryset = queryset.filter(patient__physician__user=user)
        return queryset

""" def patient_update(request, pk):
    patient = Patient.objects.get(id=pk)
    form = PatientForm()
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            patient.first_name = first_name
            patient.last_name = last_name
            patient.age = age
            patient.save()
            return redirect("/patients")
    context = {
        "form" : form,
        "patient" : patient
    }
    return render(request, "patients/patient_update.html",context)
 """

patients/templates/patients/assign_physician.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-sm mx-auto">
    <a class="hover:text-blue-500" href="{% url 'patients:patient-list' %}">Back</a>
    <hr />
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-2xl text-gray-800">Assign a physician to this patient</h1>
    </div>
    <form class="mt-5" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit"  class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
    
</div>
    

{% endblock content %}

patients/templates/patients/followup_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'patients:patient-detail' patient.pk %}">Go back to {{ patient }}</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new followup</h1>
    </div>
    <form method="post" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

patients/templates/patients/followup_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'patients:patient-detail' object.patient.pk %}">Back</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Are you sure you want to delete this followup?</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

patients/templates/patients/followup_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'patients:patient-detail' object.patient.pk %}">Back</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update this followup</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
    <div class="mt-5 pt-5 border-t border-gray-200">
        <a href="{% url 'patients:patient-followup-delete' object.pk %}" class="text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md">
            Delete
        </a>
    </div>
</div>

{% endblock content %}

patients/templates/patients/patient_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'patients:patient-list' %}">Back</a>
    <hr />
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new patient</h1>
    </div>

    <form method="POST" class="mt-5">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>

</div>


{% endblock content %}

patients/templates/patients/patient_delete.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'patients:patient-list' %}">Back</a>
    <hr />
    <h1>Deleting patient </h1>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit">Confirm</button>
    </form>
    

{% endblock content %}

patients/templates/patients/patient_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <div class="w-full flex items-center justify-between space-x-6">
                    <div class="flex-1 truncate">
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">PATIENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ patient.first_name }} {{ patient.last_name }}</h1>

                    </div>
                    {% if patient.profile_picture %}
                    <img class="w-10 h-10 bg-gray-300 rounded-full flex-shrink-0"
                        src="{{ patient.profile_picture.url }}" alt="">
                    {% endif %}
                </div>
                <div class="flex mb-4">
                    <a href="{% url 'patients:patient-detail' patient.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Details
                    </a>
                    <a href="{% url 'patients:patient-update' patient.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update
                    </a>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{ patient.age }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{ patient.email }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Phone Number</span>
                    <span class="ml-auto text-gray-900">{{ patient.phone_number }}</span>
                </div>
            </div>    
        </div>
        <div class="lg:w-4/5 mx-auto">
            <a href="{% url 'patients:patient-followup-create' patient.pk %}"
                class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Add a followup</a>
        {% for followup in patient.followups.all %}
        
        <div class="mt-5 shadow px-4 sm:px-6">
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                <dt class="text-sm font-medium text-gray-500">
                    Messages (<a href="{% url 'patients:patient-followup-update' followup.pk %}"
                        class="text-blue-500 hover:text-blue-700">update</a>)
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ followup.message }}
                </dd>
            </div>
            {% if followup.file %}
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                <dt class="text-sm font-medium text-gray-500">
                    Attachments
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
                        <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                            <div class="w-0 flex-1 flex items-center">
                                <!-- Heroicon name: paper-clip -->
                                <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd"
                                        d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z"
                                        clip-rule="evenodd" />
                                </svg>
                                <span class="ml-2 flex-1 w-0 truncate">
                                    {{ followup.file.name }}
                                </span>
                            </div>
                            <div class="ml-4 flex-shrink-0">
                                <a href="{{ followup.file.url }}" download
                                    class="font-medium text-indigo-600 hover:text-indigo-500">
                                    Download
                                </a>
                            </div>
                        </li>
                    </ul>
                </dd>
            </div>
            {% endif %}
        </div>
        {% endfor %}
        </div>
        
    </div>
</section>

{% endblock content %}

patients/templates/patients/patient_list.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Patients</h1>
            </div>
            {% if request.user.is_teamlead %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'patients:patient-create' %}">
                    Add a new patient
                </a>
            </div>
            {% endif %}
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Age
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Assigned to
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            Action <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for patient in patients %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="{% url 'patients:patient-detail' patient.pk %}">{{ patient.first_name }} {{ patient.last_name}}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ patient.age }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{patient.physician.user.first_name}} {{patient.physician.user.last_name}}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium">
                                    <a href="{% url 'patients:patient-update' patient.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>
                            </tr>

                        {% empty %}

                        <p>There are currently no patients</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
  
        {% if unassigned_patients.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned patients</h1>
                </div>
                {% for patient in unassigned_patients %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ patient.first_name }} {{ patient.last_name }}
                            </h2>
                            <a href="{% url 'patients:assign-physician' patient.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an physician
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>


<!-- <a href="{% url 'patients:patient-create' %}">
    Add new patient
</a>
<hr />
<h1>This is all of the patients</h1>
<ul>
    {% for patient in patients %}
    <li>
        <a href="{% url 'patients:patient-detail' patient.pk %}">{{patient.first_name}} {{patient.last_name}}</a> :
        {{patient.age}}
    </li>
    {% endfor %}
</ul> -->
{% endblock content %}

patients/templates/patients/patient_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">PATIENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ patient.first_name }} {{ patient.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'patients:patient-detail' patient.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
                        <a href="{% url 'patients:patient-update' patient.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'patients:patient-delete' patient.pk %}" class="w-1/2 mt-3 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}